FROM node:20.13.1-alpine

# Instalar pnpm
RUN npm install -g pnpm

# Crear directorio de trabajo
WORKDIR /app

# Copiar archivos de configuración
COPY package.json pnpm-lock.yaml* ./

# Instalar dependencias
RUN pnpm install

# Copiar el resto del código
COPY . .

# Generar cliente de Prisma
RUN pnpm prisma:generate

# Exponer puerto
EXPOSE 3000

# Comando para desarrollo con hot reload
CMD ["pnpm", "dev"]